# Generated by Django 4.0.6 on 2022-12-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataPegawai',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('gaji', models.CharField(max_length=100)),
                ('jeniskelamin', models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=100, null=True)),
            ],
        ),
    ]
