# Generated by Django 4.0.6 on 2022-12-28 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapegawai',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 12, 28, 5, 10, 58, 657113, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapegawai',
            name='note',
            field=models.TextField(default=datetime.datetime(2022, 12, 28, 5, 11, 12, 960058, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
